name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: Run checks
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, 'from changeset-release/') }}
    runs-on: srv-obin-ch_ubuntu-latest

    steps:
      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v6

      - name: Set up Go
        uses: https://code.forgejo.org/actions/setup-go@v6
        with:
          go-version-file: '.tool-versions'

      - name: Install dependencies
        run: go mod download

      - name: Lint code
        uses: https://github.com/golangci/golangci-lint-action@v9
        with:
          version: v2.12.2

      - name: Run tests
        run: go test ./...

      - name: Build project
        run: go build -o undercov ./cmd/undercov
