name: Release-Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    name: Create Release PR
    runs-on: srv-obin-ch_ubuntu-latest

    steps:
      - name: Run release-please
        uses: https://github.com/googleapis/release-please-action@v4
        with:
          release-type: go
          config-file: .release-please.json
          target-branch: main
          token: ${{ github.token }}
          github-api-url: ${{ github.api_url }}
          github-graphql-url: ${{ github.api_url }}
          changelog-host: ${{ github.server_url }}
